-- example of data modules 

local BlocksData = {
	Oak_Log = {
		Name = "Oak Log",
		Hardness = 2,
		BlastResistance = 2,
		Type = "Oak"
	},
	Dark_Oak_Leaves = {
		Name = "Dark Oak Leaves",
		Hardness = 0.2,
		BlastResistance = 0.2,
		Type = "Leaves"
	},
	Stone = {
		Name = "Stone",
		Hardness = 1.5,
		BlastResistance = 6,
		Type = "Stone"
	},
	Andesite = {
		Name = "Andesite",
		Hardness = 1.5,
		BlastResistance = 3,
		Type = "Stone"
	},
	Granite = {
		Name = "Granite",
		Hardness = 1.5,
		BlastResistance = 3,
		Type = "Stone"
	},
	Diorite = {
		Name = "Diorite",
		Hardness = 1.5,
		BlastResistance = 3,
		Type = "Stone"
	},
	Coal_Ore = {
		Name = "Coal Ore",
		Hardness = 3,
		BlastResistance = 3,
		Type = "Stone"
	},
	Iron_Ore = {
		Name = "Iron Ore",
		Hardness = 3,
		BlastResistance = 3,
		Type = "Stone"
	}
}

return BlocksData
